server:
  port: ${PORT:8085}

logging.pattern.console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(---){faint} %clr([%15.15t]){yellow} %clr(:){red} %clr(%m){faint}%n"

spring:
  application:
    name: gateway-service
  redis:
    host: 192.168.99.100
    port: 6379
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      routes:
      - id: account-service
        uri: http://localhost:8085
        predicates:
        - Path=/account/**
        filters:
        - RewritePath=/account/(?<path>.*), /$\{path}
        - name: RequestRateLimiter
          args:
              key-resolver: "#{@userKeyResolver}"
              redis-rate-limiter.replenishRate: 10
              redis-rate-limiter.burstCapacity: 20
